apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 2
  selector:
    matchLabels: {app: fraud-api}
  template:
    metadata:
      labels: {app: fraud-api}
    spec:
      serviceAccountName: sa-app
      containers:
      - name: app
        image: bennetsharwin/sentinalbank-app:initial   
        ports: [{containerPort: 8000}]
        env:
        - {name: MLFLOW_TRACKING_URI, value: "http://PROD_EC2_PRIVATE_IP:5000"}
        - {name: MLFLOW_S3_ENDPOINT_URL, value: "http://PROD_EC2_PRIVATE_IP:9000"}
        - {name: MODEL_NAME, value: "SentinalBankFraudModel"}
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: minio-creds
              key: MINIO_ROOT_USER
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio-creds
              key: MINIO_ROOT_PASSWORD
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          allowPrivilegeEscalation: false # setuid and setgid binaries disabled so can't move from current privilege.
          readOnlyRootFilesystem: false # Can't do that, we have to write temp files
          capabilities:
            drop: ["ALL"] # no more linux capabilities like raw sockets, mount, etc.
        resources:  # no more resource abuse
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: fraud-api
spec:
  selector: {app: fraud-api}
  ports: [{port: 8000, targetPort: 8000}]
  type: ClusterIP
