apiVersion: v1
kind: PersistentVolumeClaim   # stores MLflow's SQLite backend DB on persistent disk
metadata:
  name: mlflow-pvc
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
spec:
  replicas: 1
  selector:
    matchLabels: {app: mlflow}
  template:
    metadata:
      labels: {app: mlflow}
    spec:
      containers:
      - name: mlflow
        image: ghcr.io/mlflow/mlflow:v3.14.0-full
        args:
        - mlflow
        - server
        - --host
        - "0.0.0.0"
        - --port
        - "5000"
        - --backend-store-uri
        - sqlite:///mlflow/mlruns/mlflow.db
        - --default-artifact-root
        - s3://mlflow/
        ports: [{containerPort: 5000}]
        env:
        - {name: MLFLOW_S3_ENDPOINT_URL, value: "http://minio:9000"}
        - {name: MLFLOW_SERVER_ALLOWED_HOSTS, value: "mlflow,mlflow:5000,localhost,localhost:5000"}
        envFrom:
        - secretRef: {name: minio-creds}
        volumeMounts:
        - {name: mlruns, mountPath: /mlflow/mlruns}
      volumes:
      - name: mlruns
        persistentVolumeClaim: {claimName: mlflow-pvc}
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow
spec:
  selector: {app: mlflow}
  ports: [{port: 5000, targetPort: 5000}]