apiVersion: v1
kind: Secret
metadata:
  name: minio-creds
type: Opaque
stringData:           # stringData = plain text, k8s encodes it for you
  MINIO_ROOT_USER: minioadmin
  MINIO_ROOT_PASSWORD: minioadmin    # change this — it's a known vulnerability in your project