apiVersion: batch/v1
kind: Job
metadata:
  name: train-model
spec:
  backoffLimit: 2
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: sa-trainer
      containers:
      - name: train
        image: bennetsharwin/sentinalbank-trainer:1.1
        env:
        - {name: MLFLOW_TRACKING_URI, value: "http://mlflow:5000"}
        - {name: MLFLOW_S3_ENDPOINT_URL, value: "http://minio:9000"}
        envFrom:
        - secretRef: {name: minio-creds}
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop: ["ALL"]
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        volumeMounts:
        - name: artifacts
          mountPath: /app/artifacts
      volumes:
      - name: artifacts
        emptyDir: {}